################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/hex_bytes.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/osdep_KL2xZ.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/samples/readasync_baremetal.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_reader.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_reader_l3.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_transport_KL2xZ.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tm_reader.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tm_reader_async.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_param.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_strerror.c \
C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_utils.c 

OBJS += \
./source/hex_bytes.o \
./source/osdep_KL2xZ.o \
./source/readasync_baremetal.o \
./source/serial_reader.o \
./source/serial_reader_l3.o \
./source/serial_transport_KL2xZ.o \
./source/tm_reader.o \
./source/tm_reader_async.o \
./source/tmr_param.o \
./source/tmr_strerror.o \
./source/tmr_utils.o 

C_DEPS += \
./source/hex_bytes.d \
./source/osdep_KL2xZ.d \
./source/readasync_baremetal.d \
./source/serial_reader.d \
./source/serial_reader_l3.d \
./source/serial_transport_KL2xZ.d \
./source/tm_reader.d \
./source/tm_reader_async.d \
./source/tmr_param.d \
./source/tmr_strerror.d \
./source/tmr_utils.d 


# Each subdirectory must supply rules for building sources it contributes
source/hex_bytes.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/hex_bytes.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/osdep_KL2xZ.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/osdep_KL2xZ.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/readasync_baremetal.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/samples/readasync_baremetal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/serial_reader.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_reader.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/serial_reader_l3.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_reader_l3.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/serial_transport_KL2xZ.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/serial_transport_KL2xZ.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/tm_reader.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tm_reader.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/tm_reader_async.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tm_reader_async.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/tmr_param.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_param.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/tmr_strerror.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_strerror.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/tmr_utils.o: C:/ANJALI_PANCHAL/Repos/Swtree/Branches/oem/JDK-10189_Radiometer/tm/modules/mercuryapi/c/src/api/tmr_utils.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU C Compiler'
	arm-none-eabi-gcc -std=gnu99 -D__REDLIB__ -DSINGLE_THREAD_ASYNC_READ -DBARE_METAL -DCPU_MKL27Z64VLH4 -DCPU_MKL27Z64VLH4_cm0plus -DFRDM_KL27Z -DFREEDOM -DSERIAL_PORT_TYPE_UART=1 -DSDK_DEBUGCONSOLE=1 -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\board" -I../../include -I../../../src/api -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\source" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\drivers" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\device" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\CMSIS" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\utilities" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\serial_manager" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\lists" -I"C:\ANJALI_PANCHAL\Repos\Swtree\Branches\oem\JDK-10189_Radiometer\tm\modules\mercuryapi\c\kinetis_proj\FRDMKL27Z\component\uart" -Os -fno-common -g3 -Wall -c  -ffunction-sections  -fdata-sections  -ffreestanding  -fno-builtin -flto -ffat-lto-objects -fmacro-prefix-map="../$(@D)/"=. -mcpu=cortex-m0plus -mthumb -D__REDLIB__ -fstack-usage -specs=redlib.specs -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.o)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


